name: zdm_crawler

on:
  #将下面两行代码取消注释
  schedule:
    - cron: "0/20 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          mvn package
          cp ./target/zdm-0.0.1.jar ./zdm.jar
      - name: main logic
        env:
          minVoted: 6
          minComments: 4
          MIN_PUSH_SIZE: 4
          emailHost: smtp.qq.com
          emailAccount: ${{secrets.emailAccount}}
          emailPassword: ${{secrets.emailPassword}}
          spt: ${{secrets.spt}}
        run: java -jar zdm.jar
      - name: git add files
        run: |
          git add pushed.txt
          git add unpushed.txt
          git add ./logs/
      - name: commit & push
        uses: actions-go/push@master
        with:
          author-email: 'androidcwy@github.com'
          author-name: 'androidcwy'
          commit-message: 'update articles'
          token: ${{ secrets.GIT_TOKEN }}